const PATTERN_FOUR_SIX = {
    tileHeight: 40,
    tileWidth: 28,
      coords: [
        { isMove: true, x: 0, y: 16 },
        { isMove: false, x: 0, y: 8 },
        { isMove: false, x: 2, y: 6 },
        { isMove: false, x: 10, y: 6 },
        { isMove: false, x: 16, y: 14 },
        { isMove: false, x: 20, y: 14 },
        { isMove: false, x: 20, y: 18 },
        { isMove: false, x: 28, y: 24 },
        { isMove: false, x: 28, y: 32 },
        { isMove: false, x: 26, y: 34 },
        { isMove: false, x: 18, y: 34 },
        { isMove: false, x: 12, y: 26 },
        { isMove: false, x: 8, y: 26 },
        { isMove: false, x: 8, y: 22 },
        { isMove: false, x: 0, y: 16 },
        { isMove: true, x: 0, y: 12 },
        { isMove: false, x: 8, y: 14 },
        { isMove: false, x: 12, y: 14 },
        { isMove: false, x: 18, y: 6 },
        { isMove: false, x: 26, y: 6 },
        { isMove: false, x: 28, y: 8 },
        { isMove: false, x: 28, y: 16 },
        { isMove: false, x: 20, y: 22 },
        { isMove: false, x: 20, y: 26 },
        { isMove: false, x: 16, y: 26 },
        { isMove: false, x: 10, y: 34 },
        { isMove: false, x: 2, y: 34 },
        { isMove: false, x: 0, y: 32 },
        { isMove: false, x: 0, y: 24 },
        { isMove: false, x: 8, y: 18 },
        { isMove: false, x: 8, y: 14 },
        { isMove: true, x: 8, y: 14 },
        { isMove: false, x: 6, y: 6 },
        { isMove: false, x: 6, y: 2 },
        { isMove: false, x: 8, y: 0 },
        { isMove: false, x: 12, y: 4 },
        { isMove: false, x: 16, y: 4 },
        { isMove: false, x: 20, y: 0 },
        { isMove: false, x: 22, y: 2 },
        { isMove: false, x: 22, y: 6 },
        { isMove: false, x: 20, y: 14 },
        { isMove: false, x: 28, y: 12 },
        { isMove: false, x: 28, y: 16 },
        { isMove: true, x: 0, y: 28 },
        { isMove: false, x: 8, y: 26 },
        { isMove: false, x: 6, y: 34 },
        { isMove: false, x: 6, y: 38 },
        { isMove: false, x: 8, y: 40 },
        { isMove: false, x: 12, y: 36 },
        { isMove: false, x: 16, y: 36 },
        { isMove: false, x: 20, y: 40 },
        { isMove: false, x: 22, y: 38 },
        { isMove: false, x: 22, y: 34 },
        { isMove: false, x: 20, y: 26 },
        { isMove: false, x: 28, y: 28 },
        { isMove: true, x: 10, y: 6 },
        { isMove: false, x: 12, y: 4 },
        { isMove: true, x: 18, y: 6 },
        { isMove: false, x: 16, y: 4 },
        { isMove: true, x: 10, y: 34 },
        { isMove: false, x: 12, y: 36 },
        { isMove: true, x: 18, y: 34 },
        { isMove: false, x: 16, y: 36 }
      ]
  }
  export default PATTERN_FOUR_SIX;