const PATTERN_MAIN = {
  tileHeight: 36,
  tileWidth: 36,
  coords: [
    { isMove: true, x: 0, y: 18 },
    { isMove: false, x: 2, y: 14 },
    { isMove: false, x: 16, y: 14 },
    { isMove: false, x: 30, y: 0 },
    { isMove: false, x: 32, y: 2 },
    { isMove: false, x: 32, y: 4 },
    { isMove: false, x: 34, y: 4 },
    { isMove: false, x: 36, y: 6 },
    { isMove: false, x: 22, y: 20 },
    { isMove: false, x: 22, y: 34 },
    { isMove: false, x: 18, y: 36 },
    { isMove: false, x: 14, y: 34 },
    { isMove: false, x: 14, y: 20 },
    { isMove: false, x: 0, y: 6 },
    { isMove: false, x: 2, y: 4 },
    { isMove: false, x: 4, y: 4 },
    { isMove: false, x: 4, y: 2 },
    { isMove: false, x: 6, y: 0 },
    { isMove: false, x: 20, y: 14 },
    { isMove: false, x: 34, y: 14 },
    { isMove: false, x: 36, y: 18 },
    { isMove: false, x: 34, y: 22 },
    { isMove: false, x: 20, y: 22 },
    { isMove: false, x: 6, y: 36 },
    { isMove: false, x: 4, y: 34 },
    { isMove: false, x: 4, y: 32 },
    { isMove: false, x: 2, y: 32 },
    { isMove: false, x: 0, y: 30 },
    { isMove: false, x: 14, y: 16 },
    { isMove: false, x: 14, y: 2 },
    { isMove: false, x: 18, y: 0 },
    { isMove: false, x: 22, y: 2 },
    { isMove: false, x: 22, y: 16 },
    { isMove: false, x: 36, y: 30 },
    { isMove: false, x: 34, y: 32 },
    { isMove: false, x: 32, y: 32 },
    { isMove: false, x: 32, y: 34 },
    { isMove: false, x: 30, y: 36 },
    { isMove: false, x: 16, y: 22 },
    { isMove: false, x: 2, y: 22 },
    { isMove: false, x: 0, y: 18 },
    { isMove: true, x: 0, y: 10 },
    { isMove: false, x: 10, y: 10 },
    { isMove: false, x: 10, y: 0 },
    { isMove: true, x: 0, y: 26 },
    { isMove: false, x: 10, y: 26 },
    { isMove: false, x: 10, y: 36 },
    { isMove: true, x: 26, y: 0 },
    { isMove: false, x: 26, y: 10 },
    { isMove: false, x: 36, y: 10 },
    { isMove: true, x: 36, y: 26 },
    { isMove: false, x: 26, y: 26 },
    { isMove: false, x: 26, y: 36 }
  ]
};

export default PATTERN_MAIN;